name: Run TDD Python Tests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URI: "postgres://postgres:postgres@postgres:5432/testdb"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install PostGres SQL dependencies
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Running TDD with nosetests
        run: nosetests

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          version: "v0.1.13"
