apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      imagePullSecrets:
      - name: all-icr-io
      restartPolicy: Always
      containers:
      - name: inventory
        image: de.icr.io/nyu-devops-inventory/inventory:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8000
        resources:
          limits:
            cpu: "0.20"
            memory: "64Mi"
          requests:
            cpu: "0.10"        
            memory: "32Mi"
